\ Each new term in the Fibonacci sequence is generated by 
\ adding the previous two terms. By starting with 1 and 2, 
\ the first 10 terms will be: 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
\ By considering the terms in the Fibonacci sequence 
\ whose values do not exceed four million, find the sum 
\ of the even-valued terms.

variable ans
2 ans !

: even
	dup 2 mod 0 = if dup ans @ + ans ! else then
;

: chck 
	begin dup 4000000 < while dup rot + even repeat
;

1 2 chck 2drop
.( ans= ) ans ? cr